apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pythoncourse
  annotations:
    github.com/project-slug: vaibhavisalvi/pythoncourse
spec:
  type: other
  lifecycle: unknown
  owner: mowx
